// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTicket.Infrastructure.AppDbContext;

#nullable disable

namespace MovieTicket.Infrastructure.Migrations
{
    [DbContext(typeof(AppMovieTickerDbContext))]
    [Migration("20260408153930_UpdateRolesAndCinemaForAccount")]
    partial class UpdateRolesAndCinemaForAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieTicket.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<int?>("CinemaId")
                        .HasColumnType("int")
                        .HasColumnName("cinema_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__46A222CD72F2C3F9");

                    b.HasIndex("CinemaId");

                    b.HasIndex(new[] { "Email" }, "UQ__Accounts__AB6E6164EE02E64B")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "Phone" }, "UQ__Accounts__B43B145F1057CB3A")
                        .IsUnique()
                        .HasFilter("[phone] IS NOT NULL");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.AccountRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PK__AccountR__3213E83F3BE93F40");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRole", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int?>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("ShowID");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BookingId")
                        .HasName("PK__Booking__73951ACDEE353034");

                    b.HasIndex("ShowId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.BookingProduct", b =>
                {
                    b.Property<int>("BookingProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingProductId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPriceBookingProduct")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BookingProductId")
                        .HasName("PK__BookingP__8AFEF455DB05F0CA");

                    b.HasIndex("BookingId");

                    b.HasIndex("ProductId");

                    b.ToTable("BookingProduct", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.BookingSeat", b =>
                {
                    b.Property<int>("BookingSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingSeatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingSeatId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("HoldUntil")
                        .HasColumnType("datetime");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("SeatID");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("ShowID");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<decimal?>("TicketPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BookingSeatId")
                        .HasName("PK__BookingS__FA4B942630564FAF");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId");

                    b.ToTable("BookingSeat", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Cinema", b =>
                {
                    b.Property<int>("CinemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CinemaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CinemaId"));

                    b.Property<string>("CinemaName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CityAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("CinemaId")
                        .HasName("PK__Cinema__59C9262697EE2F56");

                    b.HasIndex("CityId");

                    b.ToTable("Cinema", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.CinemaHall", b =>
                {
                    b.Property<int>("HallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HallID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HallId"));

                    b.Property<int?>("CinemaId")
                        .HasColumnType("int")
                        .HasColumnName("CinemaID");

                    b.Property<string>("HallName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("HallId")
                        .HasName("PK__CinemaHa__7E60E2748CC49DFC");

                    b.HasIndex("CinemaId");

                    b.ToTable("CinemaHall", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.CinemaHallSeat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SeatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int?>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("HallID");

                    b.Property<int?>("PairId")
                        .HasColumnType("int")
                        .HasColumnName("PairID");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("SeatPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SeatType")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("SeatId")
                        .HasName("PK__CinemaHa__311713D347655F51");

                    b.HasIndex("HallId");

                    b.ToTable("CinemaHallSeat", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CityId")
                        .HasName("PK__City__F2D21A964D499A0D");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.LikeMovie", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("MovieID");

                    b.Property<bool?>("IsLiked")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "MovieId")
                        .HasName("PK__LikeMovi__A335E5EF7319EB51");

                    b.HasIndex("MovieId");

                    b.ToTable("LikeMovie", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_info");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("login_time")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("HistoryId")
                        .HasName("PK__LoginHis__096AA2E9C6FFBA14");

                    b.HasIndex("AccountId");

                    b.ToTable("LoginHistory", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MovieID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieActor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MovieAge")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MovieDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieGenre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MovieLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("MovieReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("MovieRuntime")
                        .HasColumnType("int");

                    b.Property<string>("MovieTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MovieTrailler")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MovieId")
                        .HasName("PK__Movie__4BD2943A61565677");

                    b.ToTable("Movie", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("DateSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IPAddress");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E329C748D74");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Otp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("otp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("otp_hash");

                    b.Property<string>("Purpose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("purpose");

                    b.Property<bool?>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("used");

                    b.HasKey("OtpId")
                        .HasName("PK__OTPs__AEE35435EEDB761D");

                    b.HasIndex("AccountId");

                    b.ToTable("OTPs", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A587FAC96A3");

                    b.HasIndex("BookingId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("permission_name");

                    b.HasKey("PermissionId")
                        .HasName("PK__Permissi__E5331AFA7EADD613");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ImageProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ProductPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__B40CC6ED714480AB");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken1")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("refresh_token");

                    b.HasKey("TokenId")
                        .HasName("PK__RefreshT__CB3C9E17FDA18B1A");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_type");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__760965CC90713F13");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PK__RolePerm__3213E83FD957185C");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShowID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowId"));

                    b.Property<int?>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("HallID");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("MovieID");

                    b.Property<DateOnly?>("ShowDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("ShowTime")
                        .HasColumnType("time");

                    b.HasKey("ShowId")
                        .HasName("PK__Show__6DE3E0D22611764A");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Show", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370FF8267C82");

                    b.HasIndex("AccountId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoucherID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRestricted")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("VoucherId")
                        .HasName("PK__Voucher__3AEE79C1C5C1E2B9");

                    b.HasIndex(new[] { "Code" }, "UQ__Voucher__A25C5AA7A3652744")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.VoucherUsage", b =>
                {
                    b.Property<int>("VoucherUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoucherUsageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherUsageId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int")
                        .HasColumnName("VoucherID");

                    b.HasKey("VoucherUsageId")
                        .HasName("PK__VoucherU__4264F82BCCE06F4C");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherUsage", (string)null);
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Account", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Cinema", "Cinema")
                        .WithMany("Accounts")
                        .HasForeignKey("CinemaId")
                        .HasConstraintName("FK_Account_Cinema");

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.AccountRole", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__AccountRo__accou__151B244E");

                    b.HasOne("MovieTicket.Domain.Entities.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__AccountRo__role___160F4887");

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Booking", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Show", "Show")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowId")
                        .HasConstraintName("FK__Booking__ShowID__17036CC0");

                    b.HasOne("MovieTicket.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Booking__UserID__17F790F9");

                    b.Navigation("Show");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.BookingProduct", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingProducts")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__BookingPr__Booki__18EBB532");

                    b.HasOne("MovieTicket.Domain.Entities.Product", "Product")
                        .WithMany("BookingProducts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__BookingPr__Produ__19DFD96B");

                    b.Navigation("Booking");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.BookingSeat", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__BookingSe__Booki__1AD3FDA4");

                    b.HasOne("MovieTicket.Domain.Entities.CinemaHallSeat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .HasConstraintName("FK__BookingSe__SeatI__1BC821DD");

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Cinema", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.City", "City")
                        .WithMany("Cinemas")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK__Cinema__CityID__1CBC4616");

                    b.Navigation("City");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.CinemaHall", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Cinema", "Cinema")
                        .WithMany("CinemaHalls")
                        .HasForeignKey("CinemaId")
                        .HasConstraintName("FK__CinemaHal__Cinem__1DB06A4F");

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.CinemaHallSeat", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.CinemaHall", "Hall")
                        .WithMany("CinemaHallSeats")
                        .HasForeignKey("HallId")
                        .HasConstraintName("FK__CinemaHal__HallI__1EA48E88");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.LikeMovie", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Movie", "Movie")
                        .WithMany("LikeMovies")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__LikeMovie__Movie__1F98B2C1");

                    b.HasOne("MovieTicket.Domain.Entities.User", "User")
                        .WithMany("LikeMovies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__LikeMovie__UserI__208CD6FA");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.LoginHistory", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Account", "Account")
                        .WithMany("LoginHistories")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__LoginHist__accou__2180FB33");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__22751F6C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Otp", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Account", "Account")
                        .WithMany("Otps")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__OTPs__account_id__236943A5");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Payment__Booking__245D67DE");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__RefreshTo__accou__25518C17");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("FK__RolePermi__permi__2645B050");

                    b.HasOne("MovieTicket.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__RolePermi__role___2739D489");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Show", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.CinemaHall", "Hall")
                        .WithMany("Shows")
                        .HasForeignKey("HallId")
                        .HasConstraintName("FK__Show__HallID__282DF8C2");

                    b.HasOne("MovieTicket.Domain.Entities.Movie", "Movie")
                        .WithMany("Shows")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK__Show__MovieID__29221CFB");

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.User", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__account_i__2A164134");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.VoucherUsage", b =>
                {
                    b.HasOne("MovieTicket.Domain.Entities.User", "User")
                        .WithMany("VoucherUsages")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__VoucherUs__UserI__2B0A656D");

                    b.HasOne("MovieTicket.Domain.Entities.Voucher", "Voucher")
                        .WithMany("VoucherUsages")
                        .HasForeignKey("VoucherId")
                        .HasConstraintName("FK__VoucherUs__Vouch__2BFE89A6");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("LoginHistories");

                    b.Navigation("Otps");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingProducts");

                    b.Navigation("BookingSeats");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Cinema", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("CinemaHalls");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.CinemaHall", b =>
                {
                    b.Navigation("CinemaHallSeats");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.CinemaHallSeat", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.City", b =>
                {
                    b.Navigation("Cinemas");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Movie", b =>
                {
                    b.Navigation("LikeMovies");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Product", b =>
                {
                    b.Navigation("BookingProducts");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Role", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Show", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LikeMovies");

                    b.Navigation("Notifications");

                    b.Navigation("VoucherUsages");
                });

            modelBuilder.Entity("MovieTicket.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("VoucherUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
